# Setup
title:               attacktheory
tagline:             'CTF Write-ups'
description:         'Write-ups for CTFs and stuff'
# url:                 
baseurl:             '/writeups'
paginate:            1
permalink:           :title

# About/contact
author:
  name:              Galen Lim
  url:               
  email:             jingliang.lim@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
# google_analytics_id: #UA-XXXX-Y
